tls:
  stores:
    default:
      defaultCertificate:
        certFile: "/certs/fullchain.pem"
        keyFile: "/certs/privkey.pem"
  certificates:
    - certFile: "/certs/fullchain.pem"
      keyFile: "/certs/privkey.pem"
